# Form implementation generated from reading ui file '.\Notepad.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import res  # type: ignore


class UiNotepad(object):
    def setup_ui(self, Notepad):
        Notepad.setObjectName("Notepad")
        Notepad.resize(440, 600)
        Notepad.setMinimumSize(QtCore.QSize(440, 600))
        Notepad.setMaximumSize(QtCore.QSize(440, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            ":/icons/C:/Users/Ryzen/PycharmProjects/notepad/notepad/icons/description_black_24dp.svg"),
            QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Notepad.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=Notepad)
        self.centralwidget.setObjectName("centralwidget")
        self.main = QtWidgets.QFrame(parent=self.centralwidget)
        self.main.setGeometry(QtCore.QRect(10, 10, 421, 581))
        self.main.setStyleSheet("QFrame {\n"
                                "background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba("
                                "81, 0, 135, 255),stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, "
                                "255));\n"
                                "font-family: Rubik, sans-serif;\n"
                                "color: white;\n"
                                "border-radius: 10px;\n"
                                "}")
        self.main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main.setObjectName("main")
        self.layoutWidget = QtWidgets.QWidget(parent=self.main)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 401, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.body = QtWidgets.QFrame(parent=self.layoutWidget)
        self.body.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
                                "border: 2px solid rgb(255, 255, 255);\n"
                                "border-radius: 7px;\n"
                                "color: white;")
        self.body.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.body.setObjectName("body")
        self.main_information = QtWidgets.QLabel(parent=self.body)
        self.main_information.setGeometry(QtCore.QRect(20, 20, 221, 71))
        self.main_information.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
                                            "border: none;\n"
                                            "font-size: 20pt;")
        self.main_information.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.main_information.setObjectName("main_information")
        self.verticalLayout.addWidget(self.body)
        self.tasks = QtWidgets.QFrame(parent=self.layoutWidget)
        self.tasks.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
                                 "border: 1px solid rgba(255, 255, 255, 40);\n"
                                 "border-radius: 7px;\n"
                                 "color: white;")
        self.tasks.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tasks.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tasks.setObjectName("tasks")
        self.verticalLayout.addWidget(self.tasks)
        self.close = QtWidgets.QPushButton(parent=self.main)
        self.close.setGeometry(QtCore.QRect(360, 0, 75, 30))
        self.close.setStyleSheet("border: none;")
        self.close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            ":/icons/C:/Users/Ryzen/PycharmProjects/notepad/notepad/icons/close_white_24dp.svg"),
            QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close.setIcon(icon1)
        self.close.setIconSize(QtCore.QSize(24, 24))
        self.close.setObjectName("close")
        Notepad.setCentralWidget(self.centralwidget)

        self.retranslate_ui(Notepad)
        QtCore.QMetaObject.connectSlotsByName(Notepad)

    def retranslate_ui(self, Notepad):
        _translate = QtCore.QCoreApplication.translate
        Notepad.setWindowTitle(_translate("Notepad", "Notepad"))
        self.main_information.setText(_translate("Notepad", "Hello, my friend"))
