# Form implementation generated from reading ui file '.\Note.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtGui, QtWidgets, QtCore

import res  # type: ignore


class UiNote(object):
    def setup_ui(self, Note):
        Note.setObjectName("Note")
        Note.resize(370, 260)
        Note.setMinimumSize(QtCore.QSize(370, 260))
        Note.setMaximumSize(QtCore.QSize(370, 260))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
                ":/icons/C:/Users/Ryzen/PycharmProjects/notepad/notepad/icons/description_black_24dp.svg"),
                QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Note.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=Note)
        self.centralwidget.setObjectName("centralwidget")
        self.main = QtWidgets.QFrame(parent=self.centralwidget)
        self.main.setGeometry(QtCore.QRect(0, 0, 370, 260))
        self.main.setStyleSheet("QFrame{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255),stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));\n"
"font-family: Rubik, sans-serif;\n"
"color: white;\n"
"border-radius: 15px;\n"
"}")
        self.main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main.setObjectName("main")
        self.close = QtWidgets.QPushButton(parent=self.main)
        self.close.setGeometry(QtCore.QRect(324, 10, 30, 30))
        self.close.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 1px solid rgba(255, 255, 255, 0);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/C:/Users/Ryzen/PycharmProjects/notepad/notepad/icons/close_white_24dp.svg"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close.setIcon(icon)
        self.close.setIconSize(QtCore.QSize(24, 24))
        self.close.setObjectName("close")
        self.delete_note = QtWidgets.QPushButton(parent=self.main)
        self.delete_note.setGeometry(QtCore.QRect(320, 217, 30, 30))
        self.delete_note.setStyleSheet("QPushButton {\n"
"color: white;\n"
"border: 1px solid rgba(255, 255, 255, 0);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/C:/Users/Ryzen/PycharmProjects/notepad/notepad/icons/delete_white_24dp.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete_note.setIcon(icon1)
        self.delete_note.setIconSize(QtCore.QSize(24, 24))
        self.delete_note.setObjectName("delete_note")
        self.save = QtWidgets.QPushButton(parent=self.main)
        self.save.setGeometry(QtCore.QRect(20, 220, 101, 30))
        self.save.setStyleSheet("QPushButton {\n"
"color: white;\n"
"font-family: Rubik, sans-serif;\n"
"font-weight: bold;\n"
"font-size: 12pt;\n"
"border: 1px solid rgba(255, 255, 255, 0);\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        self.save.setObjectName("save")
        self.label = QtWidgets.QLabel(parent=self.main)
        self.label.setGeometry(QtCore.QRect(120, 10, 120, 30))
        self.label.setStyleSheet("background-color: none; font-family: Rubik, sans-serif; font-weight: bold; font-size: 21pt;")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=self.main)
        self.widget.setGeometry(QtCore.QRect(10, 50, 350, 161))
        self.widget.setObjectName("widget")
        self.body = QtWidgets.QVBoxLayout(self.widget)
        self.body.setContentsMargins(0, 0, 0, 0)
        self.body.setObjectName("body")
        self.title = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Rubik, sans-serif")
        font.setPointSize(18)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setStyleSheet("border: none;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: white;")
        self.title.setMaxLength(25)
        self.title.setObjectName("title")
        self.body.addWidget(self.title)
        self.note = QtWidgets.QTextEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Rubik, sans-serif")
        font.setPointSize(14)
        font.setBold(True)
        self.note.setFont(font)
        self.note.setStyleSheet("border: none;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: white;")
        self.note.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.note.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.note.setObjectName("note")
        self.body.addWidget(self.note)
        Note.setCentralWidget(self.centralwidget)

        self.retranslate_ui(Note)
        QtCore.QMetaObject.connectSlotsByName(Note)

    def retranslate_ui(self, Note):
        _translate = QtCore.QCoreApplication.translate
        Note.setWindowTitle(_translate("Note", "Notepad"))
        self.delete_note.setShortcut(_translate("Note", "Del"))
        self.save.setText(_translate("Note", "Сохранить"))
        self.save.setShortcut(_translate("Note", "Return"))
        self.label.setText(_translate("Note", "Notepad"))
        self.title.setPlaceholderText(_translate("Note", "Заголовок"))
        self.note.setPlaceholderText(_translate("Note", "Запись"))
